RM=rm
CD=cd
MAKE=make

all:
	${CD} api && ${MAKE} -f Makefile
	${CD} btr && ${MAKE} -f Makefile
	${CD} capms && ${MAKE} -f Makefile
	${CD} gcreq && ${MAKE} -f Makefile
	${CD} gxml && ${MAKE} -f Makefile
	${CD} hsi && ${MAKE} -f Makefile
	${CD} mpms && ${MAKE} -f Makefile
	${CD} onq && ${MAKE} -f Makefile
	${CD} opera && ${MAKE} -f Makefile
	${CD} pcard && ${MAKE} -f Makefile
	${CD} prince && ${MAKE} -f Makefile
	${CD} sdcxml && ${MAKE} -f Makefile
	${CD} svcha && ${MAKE} -f Makefile
	${CD} svs && ${MAKE} -f Makefile
	${CD} visak && ${MAKE} -f Makefile

clean:
	${CD} api && ${MAKE} -f Makefile clean
	${CD} btr && ${MAKE} -f Makefile clean
	${CD} capms && ${MAKE} -f Makefile clean
	${CD} gcreq && ${MAKE} -f Makefile clean
	${CD} gxml && ${MAKE} -f Makefile clean
	${CD} hsi && ${MAKE} -f Makefile clean
	${CD} mpms && ${MAKE} -f Makefile clean
	${CD} onq && ${MAKE} -f Makefile clean
	${CD} opera && ${MAKE} -f Makefile clean
	${CD} pcard && ${MAKE} -f Makefile clean
	${CD} prince && ${MAKE} -f Makefile clean
	${CD} sdcxml && ${MAKE} -f Makefile clean
	${CD} svcha && ${MAKE} -f Makefile clean
	${CD} svs && ${MAKE} -f Makefile clean
	${CD} visak && ${MAKE} -f Makefile clean
	${RM} -rf build
